services:
  - type: web
    name: web-marvin
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: DB_HOST
        value: tramway.proxy.rlwy.net
      - key: DB_PORT
        value: 26181
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: dvbBLreTROOhoiuKKsOfmzqbFrapwiKw
      - key: DB_NAME
        value: railway